#cloud-config
# package_update: true
# package_upgrade: true
# package_reboot_if_required: true

groups:
  - ubuntu: [root, sys]
  - hashicorp

packages:
  - git

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh-authorized-keys:
      - ${ssh_public_key}

runcmd:
  - /usr/bin/sleep 10
  - /usr/bin/docker pull tutum/hello-world
  - /usr/bin/docker run -d -p 80:80 --restart=always tutum/hello-world

final_message: "The system is finally up, after $UPTIME seconds"
